/**
 * Golden-corpus regression test for the offline classification layers.
 *
 * Loads sample-data/labeled/ (generated by scripts/generate-golden-corpus.ts — existing
 * fixtures hand-labeled with gold categories, the §1.4a adversarial probes, and generated
 * messy variants), runs each offline layer against it, prints the baseline report table +
 * confusion matrix, and fails if coverage or accuracy drop below the recorded floor.
 *
 * Local, deterministic, zero-network — see docs/classification-improvement-fable.md §4 PR-1.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import Papa from 'papaparse'
import type { Category } from './types'
import {
  evaluateLayer,
  buildConfusionMatrix,
  formatLayerReportTable,
  formatConfusionMatrix,
  merchantLookupClassifier,
  transferKeywordClassifier,
  combinedOfflineClassifier,
  type GoldTransaction,
} from './evaluate'

function loadGoldCsv(filename: string): GoldTransaction[] {
  const csv = readFileSync(resolve(__dirname, '../../sample-data/labeled', filename), 'utf8')
  const result = Papa.parse<Record<string, string>>(csv, { header: true, skipEmptyLines: true })
  return result.data.map((row) => ({
    sourceFile: row.sourceFile,
    description: row.description,
    amount: parseFloat(row.amount),
    type: row.type as 'debit' | 'credit',
    category: row.category as Category,
    subcategory: row.subcategory,
  }))
}

describe('offline classification eval harness', () => {
  let fixtureRows: GoldTransaction[]
  let adversarialRows: GoldTransaction[]
  let messyVariantRows: GoldTransaction[]
  let allRows: GoldTransaction[]

  beforeAll(() => {
    fixtureRows = loadGoldCsv('fixtures-gold.csv')
    adversarialRows = loadGoldCsv('adversarial-probes.csv')
    messyVariantRows = loadGoldCsv('messy-variants.csv')
    allRows = [...fixtureRows, ...adversarialRows, ...messyVariantRows]
  })

  it('golden corpus is the expected size and shape', () => {
    // Every existing sample-data/*.csv row (818+185=1003, matching doc §1.3's denominators),
    // the 10 §1.4a adversarial probes, and the generated messy variants.
    expect(fixtureRows.length).toBe(1003)
    expect(adversarialRows.length).toBe(10)
    expect(messyVariantRows.length).toBeGreaterThan(0)
    expect(allRows.length).toBeGreaterThanOrEqual(1000)
    expect(allRows.length).toBeLessThanOrEqual(2000)

    for (const row of allRows) {
      expect(row.description.length).toBeGreaterThan(0)
      expect(row.category.length).toBeGreaterThan(0)
    }
  })

  it('prints the baseline report and confusion matrix, and holds the recorded floors', () => {
    // Floors below are the values actually measured against this corpus + the unmodified
    // Layer 0 (transfers.ts) / Layer 1 (merchantLookup.ts) code at PR-1 time — they are NOT
    // targets, they are a regression net. A future change (e.g. PR-2's normalizer/rule
    // fixes) is expected to RAISE these numbers; when it does, update the floor constants
    // to the new measured baseline in the same PR. Fixture-only Layer 1 coverage matches
    // docs/classification-improvement-fable.md §1.3's measured 818/1003 (81.6%) exactly.
    const FIXTURE_COVERAGE_FLOOR = 0.815 // measured 818/1003 = 81.55% — doc §1.3's "≈81.6%"
    const FIXTURE_ACCURACY_FLOOR = 0.981 // measured 803/818 = 98.17% (of covered fixture rows)

    const CORPUS_LAYER1_COVERAGE_FLOOR = 0.846 // measured 1128/1333 = 84.62%
    const CORPUS_LAYER1_ACCURACY_FLOOR = 0.977 // measured 1103/1128 = 97.78%

    const CORPUS_LAYER0_COVERAGE_FLOOR = 0.044 // measured 59/1333 = 4.43%
    const CORPUS_LAYER0_ACCURACY_FLOOR = 1.0 // measured 59/59 = 100%

    const CORPUS_COMBINED_COVERAGE_FLOOR = 0.882 // measured 1176/1333 = 88.22%
    const CORPUS_COMBINED_ACCURACY_FLOOR = 0.979 // measured 1152/1176 = 97.96%

    const fixtureLayer1 = evaluateLayer('Layer 1 — merchantLookup (existing fixtures only)', fixtureRows, merchantLookupClassifier)
    const corpusLayer0 = evaluateLayer('Layer 0 — transfer keywords (full corpus)', allRows, transferKeywordClassifier)
    const corpusLayer1 = evaluateLayer('Layer 1 — merchantLookup (full corpus)', allRows, merchantLookupClassifier)
    const corpusCombined = evaluateLayer('Combined — Layer 0 then Layer 1 (full corpus)', allRows, combinedOfflineClassifier)

    const reportTable = formatLayerReportTable([fixtureLayer1, corpusLayer0, corpusLayer1, corpusCombined])
    const confusionMatrix = formatConfusionMatrix(buildConfusionMatrix(allRows, merchantLookupClassifier))

    console.log(`\nOffline classification baseline (sample-data/labeled/, ${allRows.length} rows):\n\n${reportTable}`)
    console.log(`\nLayer 1 confusion matrix (gold category vs. merchantLookup prediction):\n\n${confusionMatrix}\n`)

    expect(fixtureLayer1.coverage).toBeGreaterThanOrEqual(FIXTURE_COVERAGE_FLOOR)
    expect(fixtureLayer1.accuracy).toBeGreaterThanOrEqual(FIXTURE_ACCURACY_FLOOR)

    expect(corpusLayer1.coverage).toBeGreaterThanOrEqual(CORPUS_LAYER1_COVERAGE_FLOOR)
    expect(corpusLayer1.accuracy).toBeGreaterThanOrEqual(CORPUS_LAYER1_ACCURACY_FLOOR)

    expect(corpusLayer0.coverage).toBeGreaterThanOrEqual(CORPUS_LAYER0_COVERAGE_FLOOR)
    expect(corpusLayer0.accuracy).toBeGreaterThanOrEqual(CORPUS_LAYER0_ACCURACY_FLOOR)

    expect(corpusCombined.coverage).toBeGreaterThanOrEqual(CORPUS_COMBINED_COVERAGE_FLOOR)
    expect(corpusCombined.accuracy).toBeGreaterThanOrEqual(CORPUS_COMBINED_ACCURACY_FLOOR)
  })

  it('adversarial probes are covered (matched) but wrong — reproduces §1.4a false positives', () => {
    // These 10 descriptions are the doc's confirmed false-positive examples: the regex table
    // matches all of them with full confidence, but every match is the wrong category. This
    // pins the *current* buggy behavior so PR-2's rule fixes have a clear before/after.
    const report = evaluateLayer('adversarial probes', adversarialRows, merchantLookupClassifier)
    expect(report.coverage).toBe(1)
    expect(report.correct).toBe(0)
  })

  it('confusion matrix accounts for every row exactly once', () => {
    const matrix = buildConfusionMatrix(allRows, merchantLookupClassifier)
    let total = 0
    for (const byPrediction of matrix.values()) {
      for (const count of byPrediction.values()) total += count
    }
    expect(total).toBe(allRows.length)
  })

  it('evaluateLayer coverage/accuracy stay within [0, 1] and handle an empty corpus', () => {
    const empty = evaluateLayer('empty', [], merchantLookupClassifier)
    expect(empty.coverage).toBe(0)
    expect(empty.accuracy).toBe(0)

    for (const report of [
      evaluateLayer('fixtures', fixtureRows, merchantLookupClassifier),
      evaluateLayer('adversarial', adversarialRows, merchantLookupClassifier),
      evaluateLayer('messy', messyVariantRows, merchantLookupClassifier),
    ]) {
      expect(report.coverage).toBeGreaterThanOrEqual(0)
      expect(report.coverage).toBeLessThanOrEqual(1)
      expect(report.accuracy).toBeGreaterThanOrEqual(0)
      expect(report.accuracy).toBeLessThanOrEqual(1)
    }
  })
})
