/**
 * Golden-corpus regression test for the offline classification layers.
 *
 * Loads sample-data/labeled/ (generated by scripts/generate-golden-corpus.ts — existing
 * fixtures hand-labeled with gold categories, the §1.4a adversarial probes, and generated
 * messy variants), runs each offline layer against it, prints the baseline report table +
 * confusion matrix, and fails if coverage or accuracy drop below the recorded floor.
 *
 * Local, deterministic, zero-network — see docs/classification-improvement-fable.md §4 PR-1.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, readdirSync } from 'fs'
import { resolve } from 'path'
import Papa from 'papaparse'
import { CATEGORIES, type Category } from './types'
import { detectFormat, parseTransactions } from './parser'
import {
  evaluateLayer,
  buildConfusionMatrix,
  formatLayerReportTable,
  formatConfusionMatrix,
  merchantLookupClassifier,
  transferKeywordClassifier,
  bankCategoryClassifier,
  dictionaryClassifier,
  combinedOfflineClassifier,
  type GoldTransaction,
} from './evaluate'
import { loadMerchantDict } from './merchantDict'

const VALID_TYPES = new Set(['debit', 'credit'])
const VALID_CATEGORIES = new Set<string>(CATEGORIES)

function loadGoldCsv(filename: string): GoldTransaction[] {
  const csv = readFileSync(resolve(__dirname, '../../sample-data/labeled', filename), 'utf8')
  const result = Papa.parse<Record<string, string>>(csv, { header: true, skipEmptyLines: true })
  return result.data.map((row, i) => {
    if (!VALID_TYPES.has(row.type)) {
      throw new Error(`${filename}:${i + 2}: invalid type "${row.type}" for "${row.description}" — expected debit or credit`)
    }
    if (!VALID_CATEGORIES.has(row.category)) {
      throw new Error(`${filename}:${i + 2}: invalid category "${row.category}" for "${row.description}"`)
    }
    return {
      sourceFile: row.sourceFile,
      description: row.description,
      amount: parseFloat(row.amount),
      type: row.type as 'debit' | 'credit',
      category: row.category as Category,
      subcategory: row.subcategory,
      ...(row.bankCategory ? { bankCategory: row.bankCategory } : {}),
    }
  })
}

describe('offline classification eval harness', () => {
  let fixtureRows: GoldTransaction[]
  let adversarialRows: GoldTransaction[]
  let messyVariantRows: GoldTransaction[]
  let dictShadowRows: GoldTransaction[]
  let unseenMerchantRows: GoldTransaction[]
  let allRows: GoldTransaction[]

  beforeAll(async () => {
    fixtureRows = loadGoldCsv('fixtures-gold.csv')
    adversarialRows = loadGoldCsv('adversarial-probes.csv')
    messyVariantRows = loadGoldCsv('messy-variants.csv')
    // Not folded into allRows / the recorded floor constants below — these are dedicated
    // regression slices with their own tests (see "dictionary no longer shadows..." and
    // "dictionary honestly under-covers..." below), so adding rows to them never requires
    // hand-recomputing the unrelated aggregate floors.
    dictShadowRows = loadGoldCsv('dict-shadow-probes.csv')
    unseenMerchantRows = loadGoldCsv('unseen-merchants.csv')
    allRows = [...fixtureRows, ...adversarialRows, ...messyVariantRows]
    // dictionaryClassifier / combinedOfflineClassifier return null unconditionally until
    // the generated chunk has loaded (docs/classification-improvement-fable.md §4 PR-7).
    await loadMerchantDict()
  })

  it('golden corpus is the expected size and shape', () => {
    // Every existing sample-data/*.csv row (818+185=1003, matching doc §1.3's denominators),
    // the 10 §1.4a adversarial probes, and the generated messy variants.
    expect(fixtureRows.length).toBe(1003)
    expect(adversarialRows.length).toBe(10)
    expect(messyVariantRows.length).toBeGreaterThan(0)
    expect(allRows.length).toBeGreaterThanOrEqual(1000)
    expect(allRows.length).toBeLessThanOrEqual(2000)

    for (const row of allRows) {
      expect(row.description.length).toBeGreaterThan(0)
      expect(row.category.length).toBeGreaterThan(0)
    }
  })

  it('fixtures-gold.csv stays in sync with sample-data/*.csv (catches stale corpus edits)', () => {
    const sampleDir = resolve(__dirname, '../../sample-data')
    const topLevelCsvFiles = readdirSync(sampleDir).filter((f) => f.endsWith('.csv'))

    const goldSourceFiles = new Set(fixtureRows.map((r) => r.sourceFile))
    for (const file of topLevelCsvFiles) {
      expect(goldSourceFiles.has(file), `${file} has no rows in fixtures-gold.csv — regenerate the corpus`).toBe(true)
    }

    const rowKey = (r: { sourceFile: string; description: string; amount: number; type: string }): string =>
      `${r.sourceFile}|${r.description}|${r.amount}|${r.type}`

    const actualCounts = new Map<string, number>()
    for (const file of topLevelCsvFiles) {
      const csv = readFileSync(resolve(sampleDir, file), 'utf8')
      const result = Papa.parse<Record<string, string>>(csv, { header: true, skipEmptyLines: true })
      const headers = result.meta.fields ?? []
      const mapping = detectFormat(headers, result.data)
      const { transactions } = parseTransactions(file, result.data, mapping)
      for (const tx of transactions) {
        const key = rowKey({ sourceFile: file, description: tx.description, amount: tx.amount, type: tx.type })
        actualCounts.set(key, (actualCounts.get(key) ?? 0) + 1)
      }
    }

    const goldCounts = new Map<string, number>()
    for (const row of fixtureRows) {
      const key = rowKey(row)
      goldCounts.set(key, (goldCounts.get(key) ?? 0) + 1)
    }

    const mismatches: string[] = []
    for (const key of new Set([...actualCounts.keys(), ...goldCounts.keys()])) {
      if (actualCounts.get(key) !== goldCounts.get(key)) mismatches.push(key)
    }
    expect(mismatches, 'sample-data/*.csv has drifted from fixtures-gold.csv — regenerate the corpus').toEqual([])
  })

  it('prints the baseline report and confusion matrix, and holds the recorded floors', () => {
    // Floors below are the values actually measured against this corpus + the current
    // Layer 0 (transfers.ts) / Layer 1 (merchantLookup.ts + merchant.ts) code — they are NOT
    // targets, they are a regression net. A future change is expected to RAISE these numbers;
    // when it does, update the floor constants to the new measured baseline in the same PR.
    // Raised again by the PR-2 follow-up fix (raw-first matching pass restoring six dead
    // store-number/prefix rules, Shell/beach-city guard narrowed, ACH-credit/transfer guard) —
    // see sample-data/labeled/layer1-correct-baseline.json + the test below for the per-row
    // regression net this aggregate floor alone couldn't provide.
    // Raised again by PR-5 (bank-provided category harvesting, §4 PR-5): the FIXTURE_/
    // CORPUS_COMBINED_* floors below now include Layer 4 (bankCategoryClassifier), which
    // recovers 34 rows (monzo-uk.csv's "EMPLOYER SALARY" and bare "Amazon" — unknown to the
    // merchant dictionary, but carry a resolvable bank Category column) that Layer 0/1 alone
    // both missed. The Layer 0/1-only floors are untouched — this layer is a fallback that
    // only ever adds coverage on top of them, never competes with them.
    // Raised again by PR-7 (shipped merchant dictionary, §4 PR-7): the FIXTURE_/
    // CORPUS_COMBINED_* floors below now also include Layer 1 (dictionaryClassifier),
    // inserted ahead of the merchant regex table — see combinedOfflineClassifier. The
    // Layer 1 (regex)-only floors are untouched; the dictionary is a pure coverage add, not
    // a replacement (see the "dictionary-hit accuracy" test below for the dictionary's own
    // measured numbers).
    const FIXTURE_COVERAGE_FLOOR = 0.920 // measured 923/1003 = 92.02%
    const FIXTURE_ACCURACY_FLOOR = 0.996 // measured 920/923 = 99.67% (of covered fixture rows)

    const CORPUS_LAYER1_COVERAGE_FLOOR = 0.939 // measured 1253/1333 = 94.00%
    const CORPUS_LAYER1_ACCURACY_FLOOR = 0.997 // measured 1250/1253 = 99.76%

    const CORPUS_LAYER0_COVERAGE_FLOOR = 0.044 // measured 59/1333 = 4.43%
    const CORPUS_LAYER0_ACCURACY_FLOOR = 1.0 // measured 59/59 = 100%

    // "Combined fixture coverage ... ≥ 93%" (§4 PR-5 acceptance) — measured on the 1003
    // existing-fixture rows alone (no synthetic adversarial/messy-variant rows).
    const FIXTURE_COMBINED_COVERAGE_FLOOR = 0.997 // measured 1001/1003 = 99.80%
    const FIXTURE_COMBINED_ACCURACY_FLOOR = 0.997 // measured 999/1001 = 99.80%

    const CORPUS_COMBINED_COVERAGE_FLOOR = 0.997 // measured 1331/1333 = 99.85%
    const CORPUS_COMBINED_ACCURACY_FLOOR = 0.997 // measured 1329/1331 = 99.85%

    const fixtureLayer1 = evaluateLayer('Layer 1 — merchantLookup (existing fixtures only)', fixtureRows, merchantLookupClassifier)
    const fixtureCombined = evaluateLayer('Combined — Layer 0+dict+regex+4 (existing fixtures only)', fixtureRows, combinedOfflineClassifier)
    const corpusLayer0 = evaluateLayer('Layer 0 — transfer keywords (full corpus)', allRows, transferKeywordClassifier)
    const corpusLayer1 = evaluateLayer('Layer 1 — merchantLookup (full corpus)', allRows, merchantLookupClassifier)
    const corpusLayer4 = evaluateLayer('Layer 4 — bank category (full corpus)', allRows, bankCategoryClassifier)
    const corpusCombined = evaluateLayer('Combined — Layer 0+dict+regex+4 (full corpus)', allRows, combinedOfflineClassifier)

    const reportTable = formatLayerReportTable([
      fixtureLayer1, fixtureCombined, corpusLayer0, corpusLayer1, corpusLayer4, corpusCombined,
    ])
    const confusionMatrix = formatConfusionMatrix(buildConfusionMatrix(allRows, merchantLookupClassifier))

    console.log(`\nOffline classification baseline (sample-data/labeled/, ${allRows.length} rows):\n\n${reportTable}`)
    console.log(`\nLayer 1 confusion matrix (gold category vs. merchantLookup prediction):\n\n${confusionMatrix}\n`)

    expect(fixtureLayer1.coverage).toBeGreaterThanOrEqual(FIXTURE_COVERAGE_FLOOR)
    expect(fixtureLayer1.accuracy).toBeGreaterThanOrEqual(FIXTURE_ACCURACY_FLOOR)

    expect(fixtureCombined.coverage).toBeGreaterThanOrEqual(FIXTURE_COMBINED_COVERAGE_FLOOR)
    expect(fixtureCombined.accuracy).toBeGreaterThanOrEqual(FIXTURE_COMBINED_ACCURACY_FLOOR)

    expect(corpusLayer1.coverage).toBeGreaterThanOrEqual(CORPUS_LAYER1_COVERAGE_FLOOR)
    expect(corpusLayer1.accuracy).toBeGreaterThanOrEqual(CORPUS_LAYER1_ACCURACY_FLOOR)

    expect(corpusLayer0.coverage).toBeGreaterThanOrEqual(CORPUS_LAYER0_COVERAGE_FLOOR)
    expect(corpusLayer0.accuracy).toBeGreaterThanOrEqual(CORPUS_LAYER0_ACCURACY_FLOOR)

    expect(corpusCombined.coverage).toBeGreaterThanOrEqual(CORPUS_COMBINED_COVERAGE_FLOOR)
    expect(corpusCombined.accuracy).toBeGreaterThanOrEqual(CORPUS_COMBINED_ACCURACY_FLOOR)
  })

  it('no golden-corpus row that was correct in the recorded baseline goes wrong or missed', () => {
    // The aggregate floors above are a net, but they're loose enough that a change can
    // silently regress specific known-correct rows as long as coverage rises elsewhere
    // (aggregate up, individual rows broken) — exactly what shipped once already (a
    // normalizer change that broke six store-number/prefix rules and four golden-corpus
    // rows, masked because the floors were re-recorded at the new, lower-but-still-passing
    // aggregate). This snapshot is the per-row regression net that catches that: it's the
    // set of row keys Layer 1 got right as of the last time this file was updated
    // (sample-data/labeled/layer1-correct-baseline.json, keyed the same way as the
    // "stays in sync" test above). A row leaving this set is a real regression — fix the
    // rule, or if the change is intentional, regenerate the snapshot in the same PR.
    const baseline: string[] = JSON.parse(
      readFileSync(resolve(__dirname, '../../sample-data/labeled/layer1-correct-baseline.json'), 'utf8'),
    )
    const rowKey = (r: GoldTransaction): string => `${r.sourceFile}|${r.description}|${r.amount}|${r.type}`

    const currentlyCorrect = new Set<string>()
    for (const row of allRows) {
      if (merchantLookupClassifier(row) === row.category) currentlyCorrect.add(rowKey(row))
    }

    const regressed = baseline.filter((key) => !currentlyCorrect.has(key))
    expect(regressed, 'rows correct in the baseline snapshot that are now wrong or missed').toEqual([])
  })

  it('adversarial probes now classify correctly — PR-2 fixes the §1.4a false positives', () => {
    // These 10 descriptions are the doc's confirmed false-positive examples: at PR-1 time the
    // regex table matched all of them with full confidence, but every match was the wrong
    // category (see git history for the pre-PR-2 version of this test). PR-2's mandatory
    // qualifiers / negative guards / generic keyword layer fix every one of them.
    const report = evaluateLayer('adversarial probes', adversarialRows, merchantLookupClassifier)
    expect(report.coverage).toBe(1)
    expect(report.correct).toBe(10)
  })

  it('shipped merchant dictionary meets its PR-7 acceptance floors', () => {
    // §4 PR-7 acceptance: "Real-world-style eval slice (the labeled messy corpus from PR-1)
    // coverage ≥ 85%" — messy-variants.csv is exactly that slice (stacked processor
    // prefixes, store numbers, city suffixes over a base merchant list). Measured 300/320 =
    // 93.75%; the only misses are the 5 base merchants the corpus deliberately keeps
    // unknown to any literal merchant table (§4 PR-1's "no rule exists yet" comment in
    // scripts/generate-golden-corpus.ts) to isolate the generic-keyword layer's contribution.
    const MESSY_COVERAGE_FLOOR = 0.85
    const messy = evaluateLayer('dictionary on messy-variants.csv', messyVariantRows, dictionaryClassifier)
    expect(messy.coverage).toBeGreaterThanOrEqual(MESSY_COVERAGE_FLOOR)

    // §4 PR-7 acceptance: "Dictionary-hit accuracy ≥ 95% on gold" — measured on every row
    // the dictionary is willing to classify across the full corpus (fixtures + adversarial
    // probes + messy variants): 1129/1129 = 100%.
    const DICTIONARY_ACCURACY_FLOOR = 0.95
    const dictOnAll = evaluateLayer('dictionary on full corpus', allRows, dictionaryClassifier)
    expect(dictOnAll.covered).toBeGreaterThan(0)
    expect(dictOnAll.accuracy).toBeGreaterThanOrEqual(DICTIONARY_ACCURACY_FLOOR)

    console.log(`\nDictionary layer — messy-variants.csv: ${(messy.coverage * 100).toFixed(1)}% coverage; full corpus: ${(dictOnAll.accuracy * 100).toFixed(1)}% accuracy on ${dictOnAll.covered} hits\n`)
  })

  it('dictionary no longer shadows more-specific regex rules with coarse fallback entries (regression test — PR-7 review finding #1)', () => {
    // dict-shadow-probes.csv: bare "AMAZON"/"AMZN"/"COSTCO WHSE" dictionary fallbacks used
    // to steal descriptors that merchantLookup.ts classifies more specifically (Amazon
    // Prime -> Subscriptions, Amazon Fresh -> Groceries, AWS -> Subscriptions/Cloud
    // Storage, Costco gas pumps -> Transport), regressing behavior vs. the pre-PR-7 regex
    // table. Fixed by adding the longer override phrases to MERCHANT_SOURCES (see
    // build-merchant-dict.ts) — this must stay at 100%, not just meet a floor.
    const report = evaluateLayer('dict-shadow-probes.csv', dictShadowRows, dictionaryClassifier)
    expect(report.coverage).toBe(1)
    expect(report.correct).toBe(report.total)
  })

  it('dictionary honestly under-covers merchants absent from its own source list (contrast with the messy-variants floor above — PR-7 review finding #5)', () => {
    // messy-variants.csv is generated from the same fixture-merchant universe that
    // MERCHANT_SOURCES was hand-curated from, so its coverage above measures list overlap
    // with the dictionary's own source, not generalization to merchants it has never seen.
    // unseen-merchants.csv is a small hand-picked slice of real US/UK grocery, dining, and
    // gas-station chains absent from MERCHANT_SOURCES (a few happen to be covered by the
    // much larger merchantLookup.ts regex table already) — this is what the dictionary's
    // real-world coverage looks like against the long tail it doesn't know about: close to
    // nothing. That's expected, not a regression; it's the honest number the messy-variants
    // ≥85% floor should not be mistaken for.
    const dict = evaluateLayer('dictionary on unseen-merchants.csv', unseenMerchantRows, dictionaryClassifier)
    const combined = evaluateLayer('combined offline layers on unseen-merchants.csv', unseenMerchantRows, combinedOfflineClassifier)

    console.log(`\nUnseen-merchant slice (${unseenMerchantRows.length} rows) — dictionary: ${(dict.coverage * 100).toFixed(1)}% coverage; combined offline layers: ${(combined.coverage * 100).toFixed(1)}% coverage\n`)

    // Sanity check on the fixture itself: if this ever climbs, either MERCHANT_SOURCES grew
    // to include one of these merchants (regenerate this slice with fresh unseen ones so the
    // contrast with messy-variants stays meaningful) or something is matching by accident.
    expect(dict.coverage).toBeLessThanOrEqual(0.1)
  })

  it('shipped merchant dictionary never fires on the §1.4a adversarial probes', () => {
    // The dictionary deliberately excludes bare "Shell"/"Gap"/"Boots"/"Marathon"/"Pandora"/
    // "Steam"/"O2"/"Co-op"/"USAA" (see scripts/build-merchant-dict.ts's docstring) — a
    // regression here means MERCHANT_SOURCES reintroduced one of them.
    const report = evaluateLayer('dictionary on adversarial probes', adversarialRows, dictionaryClassifier)
    expect(report.covered).toBe(0)
  })

  it('confusion matrix accounts for every row exactly once', () => {
    const matrix = buildConfusionMatrix(allRows, merchantLookupClassifier)
    let total = 0
    for (const byPrediction of matrix.values()) {
      for (const count of byPrediction.values()) total += count
    }
    expect(total).toBe(allRows.length)
  })

  it('evaluateLayer coverage/accuracy stay within [0, 1] and handle an empty corpus', () => {
    const empty = evaluateLayer('empty', [], merchantLookupClassifier)
    expect(empty.coverage).toBe(0)
    expect(empty.accuracy).toBe(0)

    for (const report of [
      evaluateLayer('fixtures', fixtureRows, merchantLookupClassifier),
      evaluateLayer('adversarial', adversarialRows, merchantLookupClassifier),
      evaluateLayer('messy', messyVariantRows, merchantLookupClassifier),
    ]) {
      expect(report.coverage).toBeGreaterThanOrEqual(0)
      expect(report.coverage).toBeLessThanOrEqual(1)
      expect(report.accuracy).toBeGreaterThanOrEqual(0)
      expect(report.accuracy).toBeLessThanOrEqual(1)
    }
  })
})
