/**
 * Offline classification eval harness.
 *
 * Measures the zero-network classification layers (transfer keyword detection,
 * merchant regex lookup) against a golden corpus of hand-labeled transactions
 * (sample-data/labeled/, generated by scripts/generate-golden-corpus.ts).
 *
 * Local, deterministic, no network calls — see docs/classification-improvement-fable.md
 * §4 PR-1.
 */
import type { Category } from './types'
import { classifyByMerchant } from './merchantLookup'
import { detectTransfers } from './transfers'

/** A single golden-corpus row: a transaction description with its correct category. */
export interface GoldTransaction {
  sourceFile: string
  description: string
  amount: number
  type: 'debit' | 'credit'
  category: Category
  subcategory: string
}

/** A classification layer under test: predicts a category from a gold row, or null (miss). */
export type OfflineClassifier = (row: GoldTransaction) => Category | null

export interface LayerReport {
  layer: string
  total: number
  covered: number
  correct: number
  /** covered / total */
  coverage: number
  /** correct / covered — accuracy among rows the layer was willing to classify */
  accuracy: number
}

/** Evaluate one classifier against the golden corpus, returning coverage/accuracy stats. */
export function evaluateLayer(layer: string, rows: GoldTransaction[], classify: OfflineClassifier): LayerReport {
  let covered = 0
  let correct = 0

  for (const row of rows) {
    const predicted = classify(row)
    if (predicted !== null) {
      covered++
      if (predicted === row.category) correct++
    }
  }

  return {
    layer,
    total: rows.length,
    covered,
    correct,
    coverage: rows.length > 0 ? covered / rows.length : 0,
    accuracy: covered > 0 ? correct / covered : 0,
  }
}

/** Layer 1 — the static merchant regex table (merchantLookup.ts:classifyByMerchant). */
export const merchantLookupClassifier: OfflineClassifier = (row) =>
  classifyByMerchant(row.description)?.category ?? null

/**
 * Layer 0 — transfer keyword detection (transfers.ts:detectTransfers), evaluated one row
 * at a time so its cross-file amount-pairing phase (which needs multiple files' worth of
 * dated transactions) never fires; only the description-keyword phase is under test here.
 */
export const transferKeywordClassifier: OfflineClassifier = (row) => {
  const transferIds = detectTransfers([
    {
      id: 'eval',
      date: new Date(2024, 0, 1),
      description: row.description,
      amount: row.amount,
      type: row.type,
      category: 'Other',
      subcategory: '',
      sourceFile: row.sourceFile,
    },
  ])
  return transferIds.size > 0 ? 'Transfer' : null
}

/** Both zero-network layers, transfer detection first (matches the real pipeline order). */
export const combinedOfflineClassifier: OfflineClassifier = (row) =>
  transferKeywordClassifier(row) ?? merchantLookupClassifier(row)

/** predicted category, or 'MISS' for an uncovered row */
type PredictedKey = Category | 'MISS'

/** gold category -> predicted category (or 'MISS') -> count */
export type ConfusionMatrix = Map<Category, Map<PredictedKey, number>>

export function buildConfusionMatrix(rows: GoldTransaction[], classify: OfflineClassifier): ConfusionMatrix {
  const matrix: ConfusionMatrix = new Map()

  for (const row of rows) {
    const predicted: PredictedKey = classify(row) ?? 'MISS'
    let byPrediction = matrix.get(row.category)
    if (!byPrediction) {
      byPrediction = new Map()
      matrix.set(row.category, byPrediction)
    }
    byPrediction.set(predicted, (byPrediction.get(predicted) ?? 0) + 1)
  }

  return matrix
}

function pct(fraction: number): string {
  return `${(fraction * 100).toFixed(1)}%`
}

/** Render a per-layer coverage/accuracy table for console output. */
export function formatLayerReportTable(reports: LayerReport[]): string {
  const columns = ['Layer', 'Total', 'Covered', 'Coverage', 'Correct', 'Accuracy']
  const rows = reports.map((r) => [
    r.layer,
    String(r.total),
    String(r.covered),
    pct(r.coverage),
    String(r.correct),
    pct(r.accuracy),
  ])

  const widths = columns.map((col, i) => Math.max(col.length, ...rows.map((row) => row[i].length)))
  const formatRow = (cells: string[]): string =>
    cells.map((cell, i) => (i === 0 ? cell.padEnd(widths[i]) : cell.padStart(widths[i]))).join('  ')

  return [formatRow(columns), ...rows.map(formatRow)].join('\n')
}

/** Render a gold-category × predicted-category confusion matrix for console output. */
export function formatConfusionMatrix(matrix: ConfusionMatrix): string {
  const goldCategories = Array.from(matrix.keys()).sort()
  const predictedKeys = new Set<PredictedKey>()
  for (const byPrediction of matrix.values()) {
    for (const key of byPrediction.keys()) predictedKeys.add(key)
  }
  // MISS last, everything else alphabetical
  const predicted = Array.from(predictedKeys).sort((a, b) =>
    a === 'MISS' ? 1 : b === 'MISS' ? -1 : a.localeCompare(b),
  )

  const header = ['gold \\ predicted', ...predicted]
  const rows = goldCategories.map((gold) => {
    const byPrediction = matrix.get(gold)!
    return [gold, ...predicted.map((p) => String(byPrediction.get(p) ?? 0))]
  })

  const widths = header.map((col, i) => Math.max(col.length, ...rows.map((row) => row[i].length)))
  const formatRow = (cells: string[]): string =>
    cells.map((cell, i) => (i === 0 ? cell.padEnd(widths[i]) : cell.padStart(widths[i]))).join('  ')

  return [formatRow(header), ...rows.map(formatRow)].join('\n')
}
