/**
 * Shipped merchant dictionary — a build-time-generated, token-indexed lookup of literal
 * merchant identities, shipped as a lazy-loaded chunk so the initial bundle is unchanged
 * (docs/classification-improvement-fable.md §2.F / §4 PR-7). Generated by
 * scripts/build-merchant-dict.ts into merchantDict.generated.json (committed, not
 * regenerated at build time — see that script for the curated source list and the
 * rationale for which merchant names are safe to include as bare literals).
 *
 * Runs before merchantLookup.ts's regex table in the offline classification pipeline
 * (useCategorization.ts:handleFiles) — the plan's ranking places the shipped dictionary
 * immediately after Layer -1 (user corrections, not yet implemented) and ahead of the
 * regex table's generic keyword rules (docs/classification-improvement-fable.md §3).
 *
 * Lookup: a description matches an entry when the entry's token sequence appears
 * *anywhere* as a contiguous run in the description's normalized tokens (not just a
 * prefix) — trailing/leading noise (store numbers, city names, "INC"/"LLC") doesn't need
 * to be enumerated in the source list, since normalizeMerchant already strips most of it
 * and every start position is checked. Within a start position, the longest candidate
 * wins, so a specific multi-word entry (e.g. "UBER EATS") safely overrides a shorter
 * fallback (e.g. bare "UBER") without needing regex lookahead tricks.
 */
import type { Category } from './types'
import { normalizeMerchant } from './merchant'

export interface MerchantDictMatch {
  category: Category
  subcategory: string
}

interface MerchantDictEntry {
  tokens: string[]
  category: Category
  subcategory: string
}

interface MerchantDictData {
  index: Record<string, MerchantDictEntry[]>
}

let dictIndex: Record<string, MerchantDictEntry[]> | null = null
let loadPromise: Promise<void> | null = null

/**
 * Triggers the lazy chunk fetch (a no-op after the first successful call). Callers must
 * await this before classifyByDictionary can return anything but null — see
 * useCategorization.ts:handleFiles for the intended call site.
 */
export function loadMerchantDict(): Promise<void> {
  if (dictIndex) return Promise.resolve()
  if (!loadPromise) {
    loadPromise = import('./merchantDict.generated.json').then((mod) => {
      dictIndex = (mod.default as MerchantDictData).index
    })
  }
  return loadPromise
}

/** True once loadMerchantDict() has resolved — lets callers avoid firing the fetch twice. */
export function isMerchantDictLoaded(): boolean {
  return dictIndex !== null
}

// A raw description's trailing/leading "*" (e.g. "UBER* PENDING", "PAYPAL *DUNKIN" already
// has its processor prefix stripped by normalizeMerchant, but a merchant's *own* asterisk
// usage — "UBER*", "*TRIP" — is not a recognized processor prefix and survives) would
// otherwise break exact token equality against a clean dictionary entry.
function stripAsterisks(token: string): string {
  return token.replace(/^\*+|\*+$/g, '')
}

function tokensMatchAt(tokens: string[], start: number, entryTokens: string[]): boolean {
  if (start + entryTokens.length > tokens.length) return false
  for (let i = 0; i < entryTokens.length; i++) {
    if (tokens[start + i] !== entryTokens[i]) return false
  }
  return true
}

/**
 * Look up a raw bank-statement description against the shipped merchant dictionary.
 * Returns null if the dictionary hasn't finished loading yet (see loadMerchantDict) or no
 * entry matches — callers should fall back to classifyByMerchant (merchantLookup.ts).
 */
export function classifyByDictionary(rawDescription: string): MerchantDictMatch | null {
  if (!dictIndex) return null

  const { tokens } = normalizeMerchant(rawDescription)
  if (tokens.length === 0) return null

  const cleaned = tokens.map(stripAsterisks)

  for (let i = 0; i < cleaned.length; i++) {
    const candidates = dictIndex[cleaned[i]]
    if (!candidates) continue
    for (const entry of candidates) {
      if (tokensMatchAt(cleaned, i, entry.tokens)) {
        return { category: entry.category, subcategory: entry.subcategory }
      }
    }
  }

  return null
}
